add error-handling for k8s curl script

diff --git a/templates/templates-deploy-to-k8s.yml b/templates/templates-deploy-to-k8s.yml
--- a/templates/templates-deploy-to-k8s.yml
+++ b/templates/templates-deploy-to-k8s.yml
@@ -5,10 +5,16 @@
     - >
       patch_data=$(printf "[{ \"op\": \"replace\", \"path\": \"/spec/template/spec/containers/0/image\", \"value\": \"${DOCKER_IMAGE}:${DOCKER_TAG_TO_DEPLOY}\" }]")
     - >
-      curl -k
+      status_code=$(curl -k
       -X PATCH
+      -s -o /dev/null -w "%{http_code}" 
       -d "$patch_data"
       -H "Authorization: Bearer ${K8S_TOKEN}"
       -H 'Accept: application/json'
       -H 'Content-Type: application/json-patch+json'
-      "https://${K8S_SERVER_NAME}/apis/apps/v1/namespaces/${NAMESPACE}/deployments/${DEPLOYMENT}"
+      "https://${K8S_SERVER_NAME}/apis/apps/v1/namespaces/${NAMESPACE}/deployments/${DEPLOYMENT}")
+    - >
+      echo "Status Code: '$status_code'"
+    - >
+      if [[ $status_code -lt 200 || $status_code -gt 299 ]]; then echo "Error while trying to deploy new version: $status_code"; exit 1; fi
+
